Dev 1359 nginx header fix
JeevesInc/appsmith pull request #1
Opened 2022-12-19 17:45 UTC by jogendrajangid-tryjeeves

Added nginx.conf using configmap

2022-12-19 18:03 UTC, marcocaberletti requested changes

2022-12-19 18:03 UTC, marcocaberletti commented on deploy/helm/templates/statefulset.yaml
> +
to mount a single file, without "cover" all the directory, I guess we should do something like:
```
- name: nginx-config
   configMap:
      name: nginxconfig
      items:
      - key: nginx.conf
         path: nginx.conf
```

2022-12-19 18:03 UTC, marcocaberletti commented on deploy/helm/templates/statefulset.yaml
> +              mountPath: /etc/nginx/nginx.conf
Add:
```
subPath: nginx.conf
readOnly: true
```
(the reason in the comment below)

2022-12-20 05:02 UTC, jogendrajangid-tryjeeves commented on deploy/helm/templates/statefulset.yaml
> +
Done

2022-12-20 08:12 UTC, marcocaberletti requested changes

2022-12-20 08:12 UTC, marcocaberletti commented on deploy/helm/templates/nginx-configMap.yaml
> +  user www-data;
fix indentation

2022-12-20 09:21 UTC, marcocaberletti requested changes
fix format

2022-12-20 09:21 UTC, marcocaberletti commented on deploy/helm/templates/nginx-configMap.yaml
> +    worker_connections 768;
fix format

2022-12-20 10:53 UTC, marcocaberletti approved these changes

2022-12-20 11:24 UTC, merged